FROM node:20-alpine
WORKDIR /app
COPY client/package.json client/package-lock.json* ./
RUN npm install
COPY client .
RUN npm run build
EXPOSE 4173
CMD ["npm","run","preview","--","--host","0.0.0.0","--port","4173"]
